'use client'
import { Box } from '@mui/material'
import Head from 'next/head'
import CustomTextField from 'src/components/text-field'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nvt Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
     <h1>Nvt Shop</h1>
    </>
  )
}
